extern const GeoLayout thwomp_000_switch_opt1[];
extern const GeoLayout thwomp_000_switch_opt2[];
extern const GeoLayout thwomp_000_switch_opt3[];
extern const GeoLayout thwomp_geo[];
extern Lights1 thwomp_f3dlite_material_010_lights;
extern Lights1 thwomp_f3dlite_material_001_lights;
extern Lights1 thwomp_f3dlite_material_002_lights;
extern Lights1 thwomp_f3dlite_material_003_lights;
extern Lights1 thwomp_f3dlite_material_004_lights;
extern u8 thwomp_thwomp_surface_rgba16_ci8[];
extern u8 thwomp_thwomp_surface_rgba16_ci8_pal_rgba16[];
extern u8 thwomp_thwomp_face2_rgba16_ci8[];
extern u8 thwomp_thwomp_face2_rgba16_ci8_pal_rgba16[];
extern u8 thwomp_thwomp_face_rgba16_ci8[];
extern u8 thwomp_thwomp_face_rgba16_ci8_pal_rgba16[];
extern Vtx thwomp_000_displaylist_mesh_layer_1_vtx_0[103];
extern Gfx thwomp_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx thwomp_000_displaylist_mesh_layer_1_vtx_1[9];
extern Gfx thwomp_000_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_thwomp_f3dlite_material_010[];
extern Gfx mat_revert_thwomp_f3dlite_material_010[];
extern Gfx mat_thwomp_f3dlite_material_001[];
extern Gfx mat_revert_thwomp_f3dlite_material_001[];
extern Gfx mat_thwomp_f3dlite_material_002[];
extern Gfx mat_revert_thwomp_f3dlite_material_002[];
extern Gfx mat_thwomp_f3dlite_material_003[];
extern Gfx mat_revert_thwomp_f3dlite_material_003[];
extern Gfx mat_thwomp_f3dlite_material_004[];
extern Gfx mat_revert_thwomp_f3dlite_material_004[];
extern Gfx thwomp_000_displaylist_mesh_layer_1[];
extern Gfx thwomp_000_displaylist_mesh_layer_1_mat_override_f3dlite_material_002_0[];
extern Gfx thwomp_000_displaylist_mesh_layer_1_mat_override_f3dlite_material_003_1[];
extern Gfx thwomp_000_displaylist_mesh_layer_1_mat_override_f3dlite_material_004_2[];
extern Gfx thwomp_material_revert_render_settings[];
