extern const GeoLayout red_coin_geo[];
extern const GeoLayout shadow_red_coin_geo[];
extern const GeoLayout yellow_coin_geo[];
extern const GeoLayout shadow_yellow_coin_geo[];
extern const GeoLayout blue_coin_geo[];
extern const GeoLayout shadow_blue_coin_geo[];
extern const GeoLayout silver_coin_geo[];
extern const GeoLayout shadow_silver_coin_geo[];
extern Lights1 coin_red_lights;
extern u8 coin__1005860766374690857_i8[];
extern Vtx coin_Cylinder_mesh_layer_1_vtx_0[153];
extern Gfx coin_Cylinder_mesh_layer_1_tri_0[];
extern Gfx mat_coin_red[];
extern Gfx coin_Cylinder_mesh_layer_1[];
extern Gfx coin_material_revert_render_settings[];
